#!/usr/bin/python3
# coding=utf-8

# Copyright (C) 2020 Hans P. Möller <hmollercl@lubuntu.me>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

import sys
from argparse import ArgumentParser
import gettext

from lubuntubreeze import breezeconfig

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument('--version',
                        action='version',
                        version='%(prog)s 0.1')
    parser.add_argument("--data-dir",
                        dest="datadir",
                        default="/usr/share/lubuntu-breeze-config",  # modificar al final
                        help="data directory for UI files")
    parser.add_argument("--bin-dir",
                        dest="bindir",
                        default="/bin",  # modificar al final
                        help="directory where this script is, default /bin")
    options = parser.parse_args()

    # TODO translations replace gettext with _ ???
    localesApp ="lubuntu-breeze-config"
    localesDir ="/usr/share/locale"
    gettext.bindtextdomain(localesApp, localesDir)
    gettext.textdomain(localesApp)
    _ = gettext.gettext
    # to test run as "./breeze-config --data-dir data --bin-dir ."
    breezeconfig.main(sys.argv, options)